import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, RobustScaler
import joblib
import os
import logging

logger = logging.getLogger(__name__)

class MemoryReducer(BaseEstimator, TransformerMixin):
    """
    Downcasts numeric columns to float32 and int32 to save memory.
    """
    def fit(self, X, y=None):
        return self
        
    def transform(self, X):
        X = X.copy()
        for col in X.columns:
            col_type = X[col].dtype
            if col_type != object:
                c_min = X[col].min()
                c_max = X[col].max()
                if str(col_type)[:3] == 'int':
                    if c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                        X[col] = X[col].astype(np.int32)
                else:
                    if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                        X[col] = X[col].astype(np.float32)
        return X

class FeatureSelector(BaseEstimator, TransformerMixin):
    """
    Drops irrelevant or leaky features like IDs and raw timestamps.
    Also handles initial datetime feature engineering from TransactionDT if needed.
    """
    def __init__(self, cols_to_drop=None):
        self.cols_to_drop = cols_to_drop if cols_to_drop else ['TransactionID', 'TransactionDT']
        
    def fit(self, X, y=None):
        return self
        
    def transform(self, X):
        X = X.copy()
        
        # Optionally engineer time features from TransactionDT before dropping it
        # TransactionDT is in seconds from a reference datetime
        if 'TransactionDT' in X.columns:
            # Approx 86400 seconds in a day
            X['Transaction_hour'] = np.floor((X['TransactionDT'] / 3600) % 24)
            X['Transaction_day_of_week'] = np.floor((X['TransactionDT'] / 86400) % 7)
            
        drop_cols = [c for c in self.cols_to_drop if c in X.columns]
        X = X.drop(columns=drop_cols)
        return X

class FraudPreprocessor:
    def __init__(self, max_missing_pct=0.9):
        self.max_missing_pct = max_missing_pct
        self.pipeline = None
        self.num_features = []
        self.cat_features = []
        self.columns_to_keep = []

    def _build_pipeline(self):
        # Numeric pipeline: Impute with median -> Robust Scaling (handles extreme values safely)
        num_pipeline = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', RobustScaler())
        ])

        # Categorical pipeline: Impute with 'UNKNOWN' -> Ordinal Encoding
        cat_pipeline = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='constant', fill_value='UNKNOWN')),
            ('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
        ])

        preprocessor = ColumnTransformer(
            transformers=[
                ('num', num_pipeline, self.num_features),
                ('cat', cat_pipeline, self.cat_features)
            ],
            remainder='drop'  # Drop any columns not explicitly handled
        )

        # Full Pipeline: Memory reduction -> Feature Selection -> Preprocessing
        self.pipeline = Pipeline(steps=[
            ('feature_selector', FeatureSelector()),
            ('preprocessor', preprocessor)
        ])

    def fit_transform(self, df, y=None):
        logger.info("Initializing preprocessing fit_transform...")
        
        # 1. Determine features to keep based on missing percentage
        missing_pct = df.isnull().mean()
        self.columns_to_keep = missing_pct[missing_pct <= self.max_missing_pct].index.tolist()
        df_filtered = df[self.columns_to_keep]
        
        # Define base drop columns so they aren't included in num/cat features
        drop_cols = ['TransactionID', 'TransactionDT', 'isFraud']
        
        # 2. Separate numerical and categorical features
        # Note: We add 'Transaction_hour' and 'Transaction_day_of_week' generated by FeatureSelector
        X_tmp = FeatureSelector(cols_to_drop=drop_cols).fit_transform(df_filtered)
        
        self.num_features = X_tmp.select_dtypes(include=['int32', 'int64', 'float32', 'float64']).columns.tolist()
        self.cat_features = X_tmp.select_dtypes(include=['object', 'category']).columns.tolist()
        
        logger.info(f"Selected {len(self.num_features)} numerical features and {len(self.cat_features)} categorical features.")
        
        # 3. Build and fit pipeline
        self._build_pipeline()
        X_processed = self.pipeline.fit_transform(df)
        
        # Re-attach column names
        all_features = self.num_features + self.cat_features
        return pd.DataFrame(X_processed, columns=all_features, index=df.index)

    def transform(self, df):
        if self.pipeline is None:
            raise ValueError("Preprocessor has not been fitted yet.")
            
        logger.info("Transforming inference data...")
        X_processed = self.pipeline.transform(df)
        all_features = self.num_features + self.cat_features
        return pd.DataFrame(X_processed, columns=all_features, index=df.index)

    def save(self, filepath):
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        # Save both the pipeline and feature lists to ensure exact feature order during inference
        state = {
            'pipeline': self.pipeline,
            'num_features': self.num_features,
            'cat_features': self.cat_features,
            'columns_to_keep': self.columns_to_keep
        }
        joblib.dump(state, filepath)
        logger.info(f"Preprocessor saved to {filepath}")

    @classmethod
    def load(cls, filepath):
        state = joblib.load(filepath)
        instance = cls()
        instance.pipeline = state['pipeline']
        instance.num_features = state['num_features']
        instance.cat_features = state['cat_features']
        instance.columns_to_keep = state.get('columns_to_keep', [])
        return instance
